#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 29 17:08:17 2018

@author: xinhui
"""

import pandas as pd
import numpy as np

n = 4
table = np.zeros((n, n))

for i in range(n):    